spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userhotelrating
    username: root
    password: Himanshu
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
      